zendesk/racecar

exe/racecar

Before, Rails was required in order to boot a consumer. Now we try to load Rails, but if it fails we'll just continue with our business.

Only load Rails application if Rails is available

---

lib/racecar/consumer.rb
lib/racecar/runner.rb

This is configured on a per topic basis and applies to the number of bytes fetched from a single partition.

Allow configuring the max number of bytes to fetch

---

lib/racecar/runner.rb

SIGTERM is sent when the consumers are about to be reload.
Should finish processing the current message.
@dasch Please review
cc @libo

Handle SIGTERM in addition to SIGQUIT and SIGINT

---

lib/racecar/config.rb
lib/racecar/env_loader.rb
spec/env_loader_spec.rb

There's a risk that a user may typo an environment variable name and expect that the config is applied when in fact we'd be using the default value. This makes Racecar crash on startup if unknown environment variables starting with `RACECAR_` are set.

Validate that no unknown env variables have been set

---

README.md
lib/racecar/cli.rb
lib/racecar/config.rb
lib/racecar/rails_config_file_loader.rb

* Don't write to the Rails log by default.
* Default to logging on `STDOUT`.
* Allow passing in `--log LOGFILE` to configure the log file.

Allow configuring a log file

---

README.md
lib/racecar/consumer.rb
lib/racecar/runner.rb
spec/runner_spec.rb

As we're rewriting our consumers we've noticed that there's one case we can't handle with racecar right now. Some of our consumer do some cleanup when a consumer is being shut down. This PR would allow us to have the same behaviour in racecar.

call `stop` on consumer class when trapping signals

---

README.md
lib/racecar/config.rb
lib/racecar/runner.rb

Useful if e.g. your consumer groups have trouble stabilizing.

Allow setting the consumer group session timeout

---

README.md
lib/racecar/cli.rb
lib/racecar/config.rb
racecar.gemspec

Allow setting config variables through the CLI:
```
$ bundle exec racecar --help                                                                                                                               cli-config
Usage: racecar MyConsumer [options]
-r, --require LIBRARY            Require the LIBRARY before starting the consumer
-l, --log LOGFILE                Log to the specified file
--brokers VALUE              A list of Kafka brokers in the cluster that you're consuming from (default: ["localhost:9092"])
--client-id VALUE            A string used to identify the client in logs and metrics (default: "racecar")
--offset-commit-interval VALUE
How frequently to commit offset positions (default: 10)
--offset-commit-threshold VALUE
How many messages to process before forcing a …
```

Allow configuring Racecar through the CLI

---

exe/racecarctl
lib/racecar/cli.rb
lib/racecar/config.rb
lib/racecar/ctl.rb
lib/racecar/daemon.rb

Allow daemonizing the Racecar process. When executing `racecar` with the `--daemonize` flag, the process will fork off and do the daemonic dance in order to liberate itself from its terminal master. The process id (PID) of the new process will be written to a (configurable) file, which will allow tools to identify the process and send it signals. The `racecarctl` tool gets two new commands, `status` and `stop`.
Based on http://codeincomplete.com/posts/ruby-daemons/
This is done in order to support users who do not want to use process managers such as Runit or God. A Capistrano recipe could be added to automate the process management.

Allow daemonizing the process

---

lib/racecar/cli.rb

Before we would initialize the config very early in the CLI, so rails apps would not get a chance to set ENV vars in their initializers.

Defer loading of config until after rails had a chance to set ENV vars

---

exe/racecar

We might receive SIGTERM before we've had a chance to install our signal handler, resulting in the exception being raised. This gracefully handles that scenario.

Rescue SignalException at the top level

---

lib/racecar/rails_config_file_loader.rb

For some old versions of ActiveSupport, ActiveSupport::Logger does not exist.

Support older ActiveSupport versions

---

lib/racecar.rb
lib/racecar/cli.rb

* Automatically loads `config/racecar.rb` if it exists.
* Adds a nicer syntax for configuring in Ruby.
Now you can just do this:
```ruby
Racecar.configure do |config|
config.session_timeout = 10
config.group_id ||= "some-group"
end
```

Allow configuring Racecar with Ruby

---

lib/racecar/cli.rb

`logger.level=` expects INT, not a String

Fix log_level

---

lib/racecar/runner.rb
spec/runner_spec.rb

This PR fixes the `consumer_class` instrumentation param provided to the `instrumenter`. 
All event subscribers should now receive a `consumer_class` field that looks like `FooConsumer` instead of `#<FooConsumer:0x007ff7bf7cc3b0>`.

Fix `consumer_class` instrumentation field

---

lib/racecar/runner.rb

It looks like the `ssl_ca_cert_file_path` option was missed in the runner - this fixes the issue.

Pass ssl_ca_cert_file_path config to Kafka.new in runner.rb

---

README.md
examples/producing_consumer.rb
lib/racecar/consumer.rb
lib/racecar/runner.rb
spec/runner_spec.rb

This change allows consumers to produce messages. The messages will be delivered automatically after `#process` returns, in the case of single-message processing, or after `#process_batch` returns, in the case of batch processing.
The API works like this:
```ruby
class DoublingConsumer < Racecar::Consumer
subscribes_to "numbers"
def process(message)
value = Integer(message.value)
produce value * 2, topic: "doubled"
end
end
```
Closes #29.

Allow producing messages

---

README.md

Use Ruby class instead of Rails class as this is a plain Ruby class.

[Readme update] Use Ruby class instead of Rails class

---

CHANGELOG.md
README.md
lib/racecar/config.rb

In https://github.com/zendesk/ruby-kafka/pull/434, the default `max_wait_time` in ruby-kafka was changed to 1 second.
This make the corresponding change for racecar, since the default here overrides the ruby-kafka default.

Change the default max_wait_time to 1 second

---

CHANGELOG.md
README.md
lib/racecar/config.rb
lib/racecar/consumer.rb
lib/racecar/runner.rb
spec/config_spec.rb

This change exposes the `offset_retention_time` from the ruby-kafka Consumer API (https://github.com/zendesk/ruby-kafka/pull/316) for Racecar consumers.
The `offset_retention_time` can be set globally or for an individual consumer class.

Expose offset_retention_time configuration for consumers

---

README.md
racecar.gemspec

This discontinues support for Kafka 0.9.

Require ruby-kafka v0.5.0 or higher

---

lib/racecar.rb
lib/racecar/config.rb

For example:
```ruby
Racecar.configure do |config|
config.logger = Logger.new("my.log")
end
```
Fixes #71.

Allow configuring the logger on Config

---

lib/racecar/config.rb
lib/racecar/runner.rb
spec/runner_spec.rb

If processing a partition raises an exception again after a pause duration has expired, the next pause will be twice as long. This continues until either the max pause timeout is reached, or the processing succeeds.
Fixes #73.

Add support for configuring exponential pause backoff

---

lib/racecar/runner.rb
spec/runner_spec.rb

These are no longer needed by the Datadog APM integration.

Remove separate "start" instrumentation events

---

lib/racecar/config.rb
lib/racecar/runner.rb

The max size of fetch responses. Used to avoid blowing out the memory of consumers.

Allow configuring `max_bytes`

---

lib/racecar/config.rb
lib/racecar/runner.rb

Limits the number of fetch responses to keep queued.

Allow configuring `max_fetch_queue_size`

---

README.md
lib/racecar/consumer.rb
lib/racecar/runner.rb

Fixes #61.
Right now we only support async heartbeats – let's see if there's a need for a blocking version before adding it in.

Implement support for manual heartbeats

---

README.md

The documentation was incorrectly specifying that the default group_id would be a snake-case version of the consumer class name, when it in fact uses dashes.

Fix group_id/group_id_prefix documentation

---

CHANGELOG.md
lib/racecar/config.rb
lib/racecar/runner.rb

Would just like be able to use SASL authentication without SSL as my broker doesn't allow this.

Allow configuring `sasl_over_ssl`.

---

spec/cli_spec.rb
spec/config_spec.rb
spec/runner_spec.rb
spec/spec_helper.rb

This PR configures RSpec to use less monkey-patching (none of which was in use in this project, so few changes here).
> Use the `disable_monkey_patching!` configuration option to
> disable all monkey patching done by RSpec:
> 
>  -   stops exposing DSL globally
>   -  disables should and should_not syntax for rspec-expectations
>   -  disables stub, should_receive, and should_not_receive syntax for rspec-mocks
> 
See https://relishapp.com/rspec/rspec-core/v/3-8/docs/configuration/zero-monkey-patching-mode

RSpec: enable zero-monkey patch mode

---

lib/racecar/version.rb

Update version to `v0.5.0.beta2` for release.
Low.

Update version to v0.5.0.beta2

---

CHANGELOG.md
exe/racecar
lib/racecar/cli.rb

Related issue https://github.com/zendesk/racecar/issues/114
Suggested solution - https://github.com/zendesk/racecar/issues/114#issuecomment-478960548

Add current dir to LOAD_PATH only when --require option is used

---

.gitignore
lib/racecar/cli.rb
lib/racecar/config.rb
lib/racecar/runner.rb
lib/racecar/version.rb
racecar.gemspec

ruby-kafka introduce new configuration property that solve a critical issue when connecting to Heroku with SSL: [SSL verification breaks Heroku Kafka #734](https://github.com/zendesk/ruby-kafka/issues/734)
Without this fix I wasn't able to connect to heroku's Kafka with racecar...

support for ssl_verify_hostname in the configuration

---

lib/racecar/consumer_set.rb

This has been discussed in #122, although that bug is about another issue. 
In my local tests an exponential back off was not needed, since this error is apparently only triggered once when the connection is torn down.

retry transport failures instead of crashing (can happen during broker shutdown)

---

lib/racecar/message.rb
lib/racecar/runner.rb
spec/runner_spec.rb

Provides backwards compatibility and avoids leaking internals.

Wrap the rdkafka message

---

lib/racecar/consumer_set.rb
spec/consumer_set_spec.rb

As per https://github.com/zendesk/racecar/issues/122#issuecomment-530777250 , let's keep to the existing promises. 
It doesn't fix the specific issue mentioned in #122, though.

retry poll failures with exponential backoff (see #122)

---

lib/racecar/message.rb
spec/runner_spec.rb

RdKafka uses `payload`, not `value`

---

README.md

seems like it was changed in https://github.com/zendesk/racecar/pull/123
but the docs was not updated

fix Consumer#produce method interface in docs

---

README.md
lib/racecar.rb
lib/racecar/cli.rb
lib/racecar/config.rb
spec/cli_spec.rb

In the case of simple consumers, there would be no need to boot Rails to process the messages, as you wouldn't necessarily need Rails. This is particularly advantageous in larger Rails applications, which would use significantly more resources than a simple consumer running vanilla Ruby.
I benchmarked the consumer we use at the company I work for - both with and without starting Rails. With Rails it uses 282M whereas without it uses 23M, just under a 92% saving in terms of memory alone.

Add Option To Not Boot Rails When Starting Consumer

---

README.md
lib/racecar.rb
lib/racecar/cli.rb
lib/racecar/config.rb
spec/cli_spec.rb

The PR has already been merged to master: https://github.com/zendesk/racecar/pull/137.
This is to add the code to the V1 stable branch.
@dasch

Add Option To Boot Consumer Without Rails To V1

---

lib/racecar.rb
lib/racecar/cli.rb
lib/racecar/consumer.rb
lib/racecar/consumer_set.rb
lib/racecar/datadog.rb
lib/racecar/instrumenter.rb
lib/racecar/runner.rb
racecar.gemspec
spec/config_spec.rb
spec/datadog_spec.rb
spec/instrumenter_spec.rb
spec/runner_spec.rb
spec/spec_helper.rb
spec/support/mock_env.rb

Moves over `ruby-kafka` instrumentation to Racecar. There are still a lot of metrics missing from the original. I could only address what's currently exposed by `rdkafka`.
It's mostly copy/paste with a few tweaks.
Some notes for review:
* `racecar.consumer.loop.duration` is really noisy. I haven't tested how it was before, but worth taking a look.
* I'm not sure whether we should use `buffer_size:  @delivery_handles.size`. This is the local buffer and not the one from librdkafka. Hoping for some ideas.
* `join_group` and `leave_group` instrumentation might be covering more ground than what they used to in ruby-kafka.
We also need to organize this properly. Splitting subscribers looks like a natural next step.

Datadog instrumentation

---

README.md
lib/racecar/runner.rb
spec/runner_spec.rb

This ensures that the global error handler is called when a runner is configured with a pause timeout.  I've also updated the README to remove the `info` argument as I don't see `error_handler` called with it anywhere.

fix: Call error handler with exception

---

lib/racecar/datadog.rb
lib/racecar/runner.rb
spec/datadog_spec.rb
spec/runner_spec.rb

As explained in https://github.com/zendesk/ruby-kafka/pull/811 we're excited to try out racecar 2 beta but need a metric for lag in the process_batch instrumentation. It doesn't look like offset_lag will be possible initially but the time_lag metric available in the process_message metrics would be useful to us if added to the process_batch metrics
Adds time_lag to process_batch metrics.

Add time_lag metric to process_batch instrumentation_payload

---

lib/racecar/datadog.rb
racecar.gemspec

Because dogstatsd-ruby moved some constants around. I was getting these errors when running specs:
> uninitialized constant Datadog::Statsd::Connection::DEFAULT_HOST
Apply the suggestion from https://github.com/zendesk/ruby-kafka/pull/810#issuecomment-589415255
Note: Similar to the change I made in https://github.com/zendesk/ruby-kafka/pull/810 but only had to go back one minor version instead of 2.

Fix missing constant error

---

lib/racecar/cli.rb
spec/cli_spec.rb
spec/support/bad_library.rb

If a required library failed to load then the failure would be silently swallowed.  The error handling added here now sends the error message to STDERR.
This PR addresses #143 for the `master` branch.

[master] Added error handling for required libraries

---

lib/racecar/cli.rb
spec/cli_spec.rb
spec/support/bad_library.rb

If a required library failed to load then the failure would be silently swallowed.  The error handling added here now sends the error message to STDERR.
This PR addresses #143 for the `v1-stable` branch.

[v1-stable] Added error handling for required libraries

---

README.md
lib/racecar/config.rb

Add a new configuration options: `ssl_certificate_location`, `ssl_key_location` and `ssl_key_password` that will get passed down to rdkafka in order to configure the certificate location.
In order to configure properly the authentication, we need to specify a certificate path too, which we currently do not: https://github.com/edenhill/librdkafka/wiki/Using-SSL-with-librdkafka#configure-librdkafka-client
Also, per the librdkafka documentation linked above ☝️ from the client perspective, we should be sending `ssl.key.location` and `ssl.key.password` too.

SSL Configuration

---

lib/racecar/runner.rb

When exceptions were being raised by processing code, the `with_pause` method would swallow them if pausing was configured, meaning that the instrumentation code would never see the exception

Move the instrumentation of `process_message` closer

---

lib/racecar/consumer_set.rb

According to https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md this setting should be called `message.max.bytes` instead of `fetch.message.max.bytes` which explains why if you set `fetch.max.bytes` to something smaller than the default `message.max.bytes` you see this error:
```
`fetch.max.bytes` must be >= `message.max.bytes` (Rdkafka::Config::ClientCreationError)
```

Rename message.max.bytes configuration

---

CHANGELOG.md
racecar.gemspec

This change is against the v1-stable branch to create a racecar version that can be used with ruby-kafka v1.0.
I've also updated the CHANGELOG with recent changes.

Require ruby-kafka v1.0 or higher

---

lib/racecar/consumer.rb
racecar.gemspec
spec/runner_spec.rb

This should ensure backwards compatibility with Racecar v1.

Bring back `partition_key`

---

CHANGELOG.md
README.md
lib/racecar/config.rb
lib/racecar/runner.rb
spec/config_spec.rb

For use with password-secured SSL client cert keys.

Add ssl_client_cert_key_password config option

---

README.md
lib/racecar/config.rb
lib/racecar/runner.rb
spec/config_spec.rb

Based on https://github.com/zendesk/ruby-kafka/tree/master#oauthbearer
I am adding the sasl_oauth_token_provider configuration, so we can use the oauthbearer from ruby-kafka.
--- 
```
Racecar.configure do |config|
config.brokers = "localhost:9094"
config.client_id =  "client"
config.sasl_oauth_token_provider =  TokenProvider.new
config.ssl_ca_certs_from_system = true
end
```
```
I, [2020-08-12T10:43:55.007741 #51439]  INFO -- : New topics added to target list: my-topic-name
I, [2020-08-12T10:43:55.007852 #51439]  INFO -- : Fetching cluster metadata from kafka://localhost:9094
D, [2020-08-12T10:43:56.196415 #51439] DEBUG -- : Obtaining new OAuth token
I, [2020-08-12T10:43:58.037736 #51439]  INFO -- : Discovered cluster metadata; nodes: localhost:9094 (node_id=0)
I, …
```

Adding support to OAUTHBEARER authentication (sasl_oauth_token_provider)

---

lib/racecar/config.rb
lib/racecar/consumer_set.rb
lib/racecar/runner.rb
spec/config_spec.rb

Hi team! 
While checking the Statsd metrics that were being sent we noticed that the `consumer.loop.duration` was being called very frequently and apparently not respecting the `max_wait_time` configuration.
After applying the change from this PR we got the expected result! 
I think I've found the places where the configuration was being sent as seconds but they were expected to be in milliseconds:
https://github.com/zendesk/racecar/blob/c9b50bac4830e6b4f8a25a73cedaff5653c0e9d9/lib/racecar/consumer_set.rb#L16
I added this method to `Racecar::Config` to convert it, but happy to do it differently if there's a better way.
I'm also not sure how to write a good test for this change... any suggestions?
Thanks in advance!

Fix max_wait_time usage

---

.circleci/config.yml
spec/integration/README.md
spec/integration/consumer_spec.rb

Adds an initial integration test that integrates with a running Kafka cluster.
A bit messy at the moment, but will be improved over time.

Add integration test suite

---

lib/racecar/pause.rb
lib/racecar/runner.rb
spec/runner_spec.rb

This PR introduces a new `retries_count` key in the `info` hash passed to the configured error handler.
This can be useful in cases where we might want to limit the number of individual error occurrences that get reported to a exception notification service or even implement some sort of monitoring for errors.
The implementation takes advantage of the existent `Pause` class, which already keeps track of the number of times the runner had to pause for a given topic/partition.

Keep track of the number of retries when handling errors

---

CHANGELOG.md
exe/racecar
lib/racecar/cli.rb
lib/racecar/instrumenter.rb
racecar.gemspec
spec/cli_spec.rb
spec/exe/racecar_spec.rb
spec/support/bad_library.rb

- Added `spec/exe/racecar_spec`.
- Moved `rescue` out to `exe/racecar`.
- Added `"--- Caused by: ---\n"` when exception has cause(s).
- Note: moved `exe/racecar` code inside `Racecar.start` to make it possible to stub `exit` without affecting surrounding rspec when it calls `exit`.
- Added `require concurrent/utility/monotonic_time` because that test was failing due to the lack of that require on ActiveSupport 6.0.3.3.
- Moved `config` to `private`.
- Added `pry` as a development dependency.

issue #186: move rescue to exe/racecar

---

lib/racecar.rb

Require `racecar/version` so we can easily check the currently running version of Racecar in the console.
Currently it doesn't work:

Require racecar/version

---

README.md

Racecar 2.0.0 replaced the underlying `ruby-kafka` gem with `rdkafka-ruby`. This PR updates the `README.md` file to remove the remaining references to `ruby-kafka`.

[Readme] Remove and replace ruby-kafka references with Rdkafka-ruby

---

CHANGELOG.md
lib/racecar/consumer_set.rb
spec/consumer_set_spec.rb

As described in https://github.com/zendesk/racecar/issues/194, this PR updates [Racecar::ConsumerSet#reset_current_consumer](https://github.com/zendesk/racecar/blob/d095104096ee62894a3d2bd47b11821f1b43abee/lib/racecar/consumer_set.rb#L144-L146)  so we [close](https://github.com/appsignal/rdkafka-ruby/blob/main/lib/rdkafka/consumer.rb#L22-L29) the underlying RdKafka consumer before removing iits reference in the `@consumers` array. Doing this prevents a memory leak when the broker disconnects from a consumers.
cc: @dasch

[Bugfix] Close RdKafka consumer in ConsumerSet#reset_current_consumer to prevent memory leak

---

CHANGELOG.md
lib/racecar/consumer_set.rb
lib/racecar/datadog.rb
spec/consumer_set_spec.rb
spec/datadog_spec.rb

The edge case looks something like this:
1. `batch_poll` iterates just fine until a very short amount of time is left, say 1ms
2. It will trigger another `poll`, which can of course fail
3. there is no time left to do any retry, thus immediately it will immediately re-raise and let the error bubble
Since the code was tough to follow already, I decided to refactor it instead of hacking the `MIN_POLL_TRIES` feature in. I adjusted the signature of `batch_poll`, even though that is not strictly needed. It just seemed weird to require `max_wait_time`/`timeout_ms` to be passed in, while the `max_messages` was "hard"coded to `@config.fetch_messages`. It's backwards compatible.
There's also another change, since rdkafka now always gets passed the `max_wait_time` instead of the `remain_ms`. This …

fix edge case where no retries were done for batch_poll

---

racecar.gemspec

Taking into a look into the last commits of `king_konf` gem, it shouldn't be a problem updating this runtime dependency in racecar, so, this PR updates it to version 1.0

Update king_konf runtime dependency to version 1.0

---

lib/racecar/message.rb
lib/racecar/runner.rb
spec/runner_spec.rb

In a recent [PR](https://github.com/zendesk/racecar/pull/187), support was added to provide `retries_count` to the instrumentation payload, in order to define custom behaviours on error handling. However, this does not allow us to drive the consumer's behaviour based on the retries, if required.
Example usage:
- We're consuming from a topic where we don't absolutely need to process every single update successfully, however we want to allow for a few intermittent failures
```
class SemiImportantConsumer < Racecar::Consumer
MAX_RETRIES_COUNT = 5
subscribes_to "semi_important_topic"
def process(message)
data = JSON.parse(message.value)
do_some_stuff(data)
rescue StandardError => e
raise e if message.retries_count < MAX_RETRIES_COUNT
Honeybadger.notify(e)
Logger.error("Oh no we ran out of …
```

Expose retries_count on Racecar::Message

---

.github/workflows/ci.yml
.gitignore
Gemfile.lock

By adding Gemfile.lock to the repository, and `bundler-cache: true` is set in the CI configuration, the `zendesk/setup-ruby` action will take care of installing the gems too. 
Please notice the speed difference in [latest master build](https://github.com/zendesk/racecar/actions/runs/426507907) and [this PR build](https://github.com/zendesk/racecar/actions/runs/426775450).
If checking in Gemfile.lock is a concern – e.g. do we forget to test for newer versions of our dependencies – we might want to let [Dependabot](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/keeping-your-dependencies-updated-automatically) keep Gemfile.lock updated?

Better CI bundle cache

---

CHANGELOG.md
lib/racecar/config.rb
lib/racecar/consumer_set.rb

If the higher level runner Racecar::Runner was used, this makes no
difference, as it already passes the correct @config.max_wait_time_ms
value. If someone uses ConsumerSet directly, without specifying
these values, this will be a breaking change.

set correct default values for max_wait_time on poll and batch_poll

---

lib/racecar/consumer_set.rb
spec/consumer_set_spec.rb

This occurs when there is only little time left and the remain_ms
works itself out to 0ms. The error message given in this scenario
before this patch is unhelpful or misleading, and doesn't need to
be acted upon most of the time. The edge case where it matters is
if remain_ms is always 0, e.g. if the system is too slow for the
configured max_wait_time_ms. Hence the debug message to see this
more easily, though it is expected that this shows up on healthy
and properly configured systems, too.
Related to https://github.com/zendesk/racecar/pull/204 . This PR
should make the error much less likely to appear in the first place.
The test included in this PR will fail if the other PR is merged,
because it checks using the log level of the error message (it's an
easy fix, though).

silence error about no time left when there were no errors

---

lib/racecar/config.rb

Fix ssl_verify_hostname which was broken since the change to rdkafka.

Fix ssl_verify_hostname

---

docker-compose.yml

refs https://github.com/zendesk/racecar/pull/225
Without this version bump docker-compose 1.25.0 (Debian) complains about:
```
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services.broker: 'healthcheck'
Unsupported config option for services.zookeeper: 'healthcheck'
services.wait-for-healthy-services.depends_on contains an invalid type, it should be an array
```

fix docker-compose version

---

README.md
lib/racecar/config.rb
lib/racecar/consumer_set.rb
lib/racecar/runner.rb
spec/config_spec.rb
spec/support/integration_helper.rb

The statistics provided by librdkafka can be quite memory intensive, especially where an application is not doing anything with them. This PR makes the following changes:
- Allows the `statistics_interval` to be configured directly in the config
- Disables the statistics if no callback has been configured in `Rdkafka` - if nobody is listening, we don't need em

Make stats interval directly configurable, disable if no callback is set

---

.github/workflows/ci.yml
CHANGELOG.md
Dockerfile
README.md
docker-compose.yml
lib/racecar.rb
lib/racecar/cli.rb
lib/racecar/config.rb
lib/racecar/consumer.rb
lib/racecar/parallel_runner.rb
lib/racecar/runner.rb
spec/integration/consumer_spec.rb
spec/parallel_runner_spec.rb
spec/support/integration_helper.rb

The issue: https://github.com/zendesk/racecar/issues/188
Some discussion on a previous implementation approach on this PR: https://github.com/zendesk/racecar/pull/221 - this PR is an initial draft to continue the conversation.
Adds a `ConcurrentRunner`, which uses forking to allow concurrent processing:
- Adds the code in a way that does not affect existing APIs (you never know what your users will decide to depend on)
- Includes quite a big overhaul of the existing integration test so that we have a fresh topic for each spec, and we also clean up the topics at the end.
What hasn't been done yet?
- Extensive testing
- Some kind of benchmarking in a semi-realistic setup. Few possible scenarios:
- Consuming a pile of messages and writing one straight out again
- Consuming a pile of messages …

Concurrency testing using a forking approach

---

CHANGELOG.md
racecar.gemspec

This change is already in master and it has no breaking changes, I would like to get it into `v1-stable` to keep using with the latest https://github.com/zendesk/delivery_boy which already depends on `"king_konf", "~> 1.0"` (due to the latest `racecar`, so kinda circular dependency).
Thanks in advance.

Bump king_konf to v1.0 in the v1-stable branch

---

README.md
lib/racecar/heroku.rb
spec/heroku_spec.rb

Goal is to provide an easy mechanism to connect to Heroku Kafka using the ENVs provided by the broker.
Currently users have to create an initizlizer to read these ENVs and set `Racecar::Config` appropriately. Heroku Kafka provides the certificates as strings, but Racecar (RDKafka) needs them as a files.
To solve this, this solution creates the file `lib/heroku.rb`, which does all the work of parsing the ENVs and setting them to the Config appropriately. Users can just `require 'racecar/heroku'` on top of the Consumer class or in an initializer to make Racecar work with the ENVs provided by Heroku Kafka.

Native Heroku Kafka support

---

Gemfile.lock
lib/racecar/consumer_set.rb
spec/consumer_set_spec.rb

Whenever a "Not Coordinator for group" error gets thrown the consumers
get stuck and they never recover. We should be retrying once that
happens.

Handle ERR_NOT_COORDINATOR

---

CHANGELOG.md
Gemfile.lock
racecar.gemspec
spec/integration/consumer_spec.rb

My team maintains a stream processing application that uses Racecar. Recently we learned that a known issue with librdkafka 1.4.0 (https://github.com/edenhill/librdkafka/issues/2830) negatively impacts the performance of our application. The latest version of rdkafka, 0.10.0, upgrades the gem to use librdkafka 1.5.0. This PR proposes updating Racecar to use rdkafka 0.10.0.
References:
- Librdkafka 1.5.0 release notes: https://github.com/edenhill/librdkafka/releases?after=v1.6.0-PRE4
- rdkafka-ruby PR upgrading to librdkafka 1.5.0: https://github.com/appsignal/rdkafka-ruby/pull/165
I made the following changes:
- Updated `racecar.gemspec` to require rdkafka 0.10.0
- Updated test setup in spec/integration/consumer_spec.rb to explicitly create topics instead of relying on Kafka to …

Upgrade to rdkafka 0.10.0

---

.github/workflows/ci.yml
Gemfile
Gemfile.lock
lib/racecar/consumer.rb
racecar.gemspec

The "ensure inside a block without an explicit begin/end" feature is a Ruby 2.5 feature (see <https://bugs.ruby-lang.org/issues/12906>) and its usage broke racecar usage on Ruby 2.4 (#252).
By re-adding the begin/end, it all works again. To make sure it keeps working, I've also added Ruby 2.4 to the test matrix on
GitHub.
I also added a `spec.required_ruby_version` to the gemspec, to make it clear which versions are tested. I tried checking if Ruby 2.3 or older could be trivially supported, but in fact the `rdkafka` dependency also requires 2.4+ and thus it implicitly sets the minimum bound for racecar.
This is an alternative to #256.
Fixes #252
P.s: I've included the version bump, let me know if you'd prefer that I remove it.

Restore support for Ruby 2.4

---

Gemfile.lock
lib/racecar/datadog.rb
lib/racecar/runner.rb
racecar.gemspec
spec/runner_spec.rb

- dogstatsd-ruby v5 buffers metrics before sending them which means they need to be flushed on process shutdown or metrics data may be lost
- The existing `close` method now calls `flush` synchronously https://github.com/DataDog/dogstatsd-ruby/blob/master/lib/datadog/statsd.rb#L331-L334
- This update adds support for dogstatsd-ruby v5 by calling `close` when the process is stopped

Add support for dogstatsd-ruby v5

---

CHANGELOG.md
README.md
lib/racecar/config.rb
lib/racecar/runner.rb

Adds `partitioner` to configuration for Racecar v1, allowing https://github.com/zendesk/ruby-kafka/pull/884 to be used.
@dasch

Adds partitioner to configuration

---

CHANGELOG.md
README.md
lib/racecar/config.rb
lib/racecar/consumer.rb
spec/config_spec.rb

Consumers might have different batch needs.

Allow Consumer (Processor?) to overwrite global `fetch_messages` config.

---

CHANGELOG.md
lib/racecar/consumer.rb
spec/runner_spec.rb

Allow producing to a specific partition.
I have encountered a use case where I want to produce a message (a tombstone, to be specific) to the same partition a consumed message came from.
Unfortunately, there's no guarantee the consumed message was produced using the same partitioner used by Rdkafka, or the one specified by the producing consumer.
Rdkafka already allows to specify a specific partition to produce a message to, so these changes are only passing the partition provided by the Racecar API

Allow producing to a specific partition

---

spec/support/integration_helper.rb

Increment attempts counter in integration_helper
Prevent `wait_for_messages` from looping forever if a message is not published

bugfix: increment attempts counter in integration_helper

---

.github/workflows/ci.yml
CHANGELOG.md
Gemfile.lock
racecar.gemspec

Originally created here https://github.com/zendesk/racecar/pull/274
This upgrade will require us to remove support from ruby 2.4 and 2.5, given that [the rdkafka gem](https://github.com/appsignal/rdkafka-ruby) dropped support for these versions in the [latest upgrade](https://github.com/appsignal/rdkafka-ruby/blob/main/CHANGELOG.md#0110).
This PR upgrades Racecar to use version[ 0.11.1 of the rdkafka gem](https://rubygems.org/gems/rdkafka/versions/0.11.1) which bumps the Librdkafka library to the version 1.8.2 ([release notes](https://github.com/edenhill/librdkafka/blob/cfc0731617ddd6858058f31f564772202f209e72/CHANGELOG.md#librdkafka-v182
)).
The main benefit of this upgrade is to try to address some issues with hanging consumers. [librdkafka 1.8.0 release …

Upgrades rdkafka gem

---

Gemfile.lock
racecar.gemspec

Updates rdkafka-ruby to version 0.12.0.beta.1.
This version uses Librdkafka version v1.9.0-RC1 which contains several fixes https://github.com/edenhill/librdkafka/blob/v1.9.0-PRE9/CHANGELOG.md#librdkafka-v190
One of the very exciting ones being
* Fix hang in `rd_kafka_list_groups()` if there are no available brokers
to connect to ([#3705](https://github.com/edenhill/librdkafka/issues/3705)).

updates rdkafka gem to 0.12.0.beta.1

---

Gemfile.lock
racecar.gemspec

Updates `rdkafka-ruby` to `0.12.0.beta.3` which has ben updated to use librdkafka 1.9.0.RC2 with the following changes:
https://github.com/edenhill/librdkafka/compare/v1.9.0-RC1...v1.9.0-RC2

update rdkafka to 0.12.0.beta.2

---

Gemfile.lock
racecar.gemspec

Updates [librdkafka](https://github.com/edenhill/librdkafka) to v1.9.0-RC10 which applies several fixes, some of them are:
* If a metadata request triggered by `rd_kafka_metadata()` or consumer group rebalancing
encountered a non-retriable error it would not be propagated to the caller and thus
cause a stall or timeout, this has now been fixed. (@aiquestion, #3625)
* AdminAPI `DeleteGroups()` and `DeleteConsumerGroupOffsets()`:
if the given coordinator connection was not up by the time these calls were
initiated and the first connection attempt failed then no further connection
attempts were performed, ulimately leading to the calls timing out.
This is now fixed by keep retrying to connect to the group coordinator
until the connection is successful or the call times out.
Additionally, the …

update rdkafka to 0.12.0.beta.4

---

CHANGELOG.md
Gemfile.lock
racecar.gemspec

This PR updates rdkafka-ruby gem to the final 0.12.0 release https://github.com/appsignal/rdkafka-ruby/pull/201
This version uses Librdkafka version v1.9.0 which contains several fixes https://github.com/edenhill/librdkafka/blob/master/CHANGELOG.md#librdkafka-v190

Bump rdkafka

---

lib/racecar/consumer_set.rb
lib/racecar/erroneous_state_error.rb
lib/racecar/runner.rb
spec/consumer_set_spec.rb

librdkafka `rd_kafka_offsets_store()` (et.al) will now return an error for any  partition that is not currently assigned (through `rd_kafka_*assign()`). This PR aims to give more context to the error when it happens.

RD_KAFKA_RESP_ERR__STATE error

---

lib/racecar/consumer_set.rb
lib/racecar/erroneous_state_error.rb
spec/consumer_set_spec.rb

Consumer sometimes lose their assigned partition and errors when trying to store the offset.
```
WARN Racecar::ErroneousStateError Partition is no longer assigned to this consumer and the offset could not be stored for commit:
Local: Erroneous state (state)
ERROR Failed to process topic_name/partition_number at offset_start..offset_end: Partition is no longer assigned to this consumer and the offset could not be stored for commit:
Local: Erroneous state (state)
INFO Attempted to pause topic_name/partition_number, but we're not subscribed to it
```
This is caused by a change in librdkafka where consumers that call `rd_kafka_offsets_store()` (et.al) will now return an error for any partition that is not currently assigned (through rd_kafka_*assign()).
Because this is a somewhat expected …

warn when partition is not assigned to consumer

---

CHANGELOG.md

Update the text of two links to match the actual link.

Fix two links in CHANGELOG

---

CHANGELOG.md
README.md
lib/racecar/config.rb
lib/racecar/runner.rb
spec/config_spec.rb

librdkafka allows different strategies to determine the partitions.
https://docs.confluent.io/5.1.4/clients/librdkafka/CONFIGURATION_8md.html
This PR exposes `partitioner` as an option that can be directly used instead of
using the `producer` config option

Expose partitioner config option

---

examples/batch_consumer.rb

The example for batch processing is outdated for v2 since `process_batch`
receives an array of messages rather than a batch struct
```
bundle exec racecar --require examples/batch_consumer BatchConsumer
=> Starting Racecar consumer BatchConsumer...
=> Wrooooom!
=> Ctrl-C to shutdown consumer
W, [2023-01-19T14:28:58.314843 #65618]  WARN -- : ActiveSupport::Notifications not available, instrumentation is disabled
E, [2023-01-19T14:29:01.338999 #65618] ERROR -- : Failed to process messages/0 at 25004..25005: undefined method `messages' for [#<Racecar::Message:0x00000001065a3aa0 @rdkafka_message=#<Rdkafka::Consumer::Message:0x00000001065a8de8 @topic="messages", @partition=0, @payload="Payload 0", @key="Key 0", @offset=25004, @timestamp=2023-01-19 14:29:00.513 +0100, @headers={}>, …
```

Update racecar v2 batch processing example

---

CHANGELOG.md
README.md
lib/racecar.rb
lib/racecar/cli.rb
lib/racecar/config.rb
lib/racecar/ctl.rb
lib/racecar/instrumenter.rb
lib/racecar/liveness_probe.rb
lib/racecar/runner.rb
spec/config_spec.rb
spec/instrumenter_spec.rb
spec/integration/kubernetes_probes_spec.rb
spec/liveness_probe_spec.rb
spec/runner_spec.rb
spec/support/integration_helper.rb

This PR is functionally similar to @jbdietrich's PR #308 
The main loop of the runner touches a file and a script will exit 0 or 1 depending on whether it was touched recently enough.
Why this implementation?
- The health check is triggered by the in-built instrumentation events so doesn't clutter up the main loop code and is entirely optional.
- The 'probe' is a first class object, allowing for extensibility such as monitoring individual partition processing or rebalancing (#309)
- The script is written in Ruby, I think we agree we like more than bash and can spare the extra ~10ms of CPU to run it.
- There's some appealing refactoring and test fixes bundled with it.
This has been back-ported into Voice and will be deployed shortly. In testing it has achieved very smooth rolling deploys …

Event based Kubernetes liveness probe

---

lib/racecar/daemon.rb

File.exists? has been deprecated since Ruby 2.2 and has been removed in Ruby 3.2
Please see: https://bugs.ruby-lang.org/issues/17391

update File exist method call since exists is deprecated in Ruby 3.2

---

.github/workflows/ci.yml

This PR will add 3.1 to our ruby version matrix and remove 2.6 since it's no
longer supported for a year now

Update ruby matrix for CI

---

README.md

Several Ruby code blocks in the main README are not using syntax highlighting while others are. Ensure that all code blocks are using it to improve the readability.

Use Ruby syntax highlighting in README

---

Gemfile.lock
lib/racecar.rb
lib/racecar/cli.rb
lib/racecar/config.rb
lib/racecar/consumer_set.rb
lib/racecar/parallel_runner.rb
lib/racecar/rebalance_listener.rb
racecar.gemspec
spec/cli_spec.rb
spec/consumer_set_spec.rb
spec/integration/consumer_spec.rb
spec/integration/kubernetes_probes_spec.rb
spec/runner_spec.rb
spec/spec_helper.rb
spec/support/integration_helper.rb

TL;DR Integration specs 3x faster ~45s -> 15s
This is a huge itch-scratch PR that addresses _most_ of the issues I have with the integration specs. Hopefully we're in agreement and maybe it's an easy merge 🤞🤷😬 🗒️ 
Here's the full laundry list:
- Replace Kafka CLI with `librdkadfka` admin connection for creation and
deletion of test topics.
- Racecar::CLI implements `#stop` which is now used instead of the test
process sending `SIGINT` to itself.
- Hook into rebalance callbacks to get a fast, reliable indication of assignments for test setup, again replacing slow CLI tools.
- Use a pipe in forked consumer processes to signal assignments back to
the test.
- Tag messages with PIDs to confirm concurrency via message state.
- Reset implicitly installed signal handlers between tests.
- Reset …

Integration test performance and refactoring

---

README.md

Tiny change, the word "configuration" was misspelled in the readme file.

Fixed a typo in the readme file

---

lib/racecar/datadog.rb
lib/racecar/delivery_callback.rb
lib/racecar/producer.rb
lib/racecar/runner.rb
spec/runner_spec.rb

Currently, we lack observability to detect errors when using the Standalone Producer. This pull request introduces improvements to error handling and instrumentation in standalone producer. The primary goal is to enhance visibility into producer errors. It's using delivery callback to instrument events for both successful and failed deliveries.
Here are stats and exceptions in various scenarios
```ruby
huge = "HUGE" * 10000
#
Racecar.produce_sync(value: "test message #{Time.now}", topic: "messages")
#
#
Racecar.produce_sync(value: "test message #{Time.now}", topic: "messages", partition: 99)
#
#
Racecar.produce_sync(value: "test message #{huge} #{Time.now}", topic: "messages")
#
#
Racecar.produce_async(value: "test message #{huge} #{Time.now}", topic: "messages")
#
# …
```

Add observality for producer errors

---

lib/racecar/ctl.rb

Some rails apps might chose to not use the racecal.yml file. Let's load known
config files if they are present similar to how cli handles them

Fix config load for liveness probe

---

lib/racecar/runner.rb
spec/datadog_spec.rb
spec/runner_spec.rb

When exceptions are raised by the processing code in `process_batch`, the `with_pause` method is swallowing them, so the instrumentation does not receive the exception
This PR makes it so that the instrumentation receives the processing exceptions.

Send exceptions to `process_batch` instrumenter

---

Gemfile.lock
README.md
lib/racecar/config.rb
lib/racecar/consumer.rb
lib/racecar/consumer_set.rb
lib/racecar/rebalance_listener.rb
racecar.gemspec
spec/integration/consumer_spec.rb
spec/integration/cooperative_sticky_assignment_spec.rb
spec/integration/kubernetes_probes_spec.rb
spec/message_delivery_error_spec.rb
spec/rebalance_listener_spec.rb
spec/support/integration_helper.rb

Features:
- Support for cooperative-sticky assignment strategy
- Consumer class partition assign and revoke callbacks
Tests:
- Refactor to share a common consumer

Add support for cooperative-sticky assignment strategy

---

.github/workflows/ci.yml

Runs tests on [Ruby 3.3 (preview 2)](https://www.ruby-lang.org/en/news/2023/09/14/ruby-3-3-0-preview2-released/) to catch possible common issues before the final release.

Run tests on Ruby 3.3 (preview 2)

---

lib/racecar/rails_config_file_loader.rb

Resolves https://github.com/zendesk/racecar/issues/356
There don't appear to be any tests which cover this but I've verified that it works locally.

Resolve Rails 7.1 logger incompatibility

---

.github/workflows/ci.yml

Ruby 3.3.0 is now out, so we should swap the version in tests. Also bumps versions for checkout and setup steps.

test on final ruby 3.3 instead of preview

---

lib/racecar/config.rb
lib/racecar/consumer_set.rb
spec/consumer_set_spec.rb

The current ConsumerSet implementation will only switch topics when the current topic returns no messages after the poll timeout.
This is not practical when one or more of the topics has a 'high' message volume as the broker will always return a message and Racecar may never switch to poll the other topics.
* 'high' here means message frequency (hz) > poll interval (s).

Configurable strategy for consuming multiple topics

---

.github/workflows/ci.yml
CHANGELOG.md
Gemfile.lock
racecar.gemspec

This PR completes a couple of housekeeping items:
1. Set required Ruby to >= 3.0 in the Gemspec (2.6 is EOL, 2.7 support dropping in `rdkafka-ruby` soon, too)
2. Upgrade `rdkafka` to `~> 0.15.0`
I noticed that `rdkafka` 0.15.0 minimum Ruby is 2.7 anyway.

Upgrade `rdkafka` ~> 0.15; require Ruby 3.0 since 2.6 is EOL

---

CHANGELOG.md
README.md
lib/racecar/cli.rb
lib/racecar/config.rb
lib/racecar/datadog.rb
spec/datadog_spec.rb

This adds support for unix domain sockets with datadog statsd

feat: support uds in datadog statsd

---

lib/racecar/cli.rb
lib/racecar/config.rb

The latest beta release broke the consumer due to exception:
`NoMethodError:  undefined method 'socket_path'`
This PR should fix this

Fix datadog unix socket path

---

CHANGELOG.md
README.md
lib/racecar/config.rb
lib/racecar/ctl.rb
spec/integration/kubernetes_probes_spec.rb

Add a new configuration option that prevents the liveness probe command from loading config files.
It's possible, even common to end up Rails specific logic Racecar config files.
`Racecar.config.logger = Rails.logger` for example.
In these cases it's not desirable for the liveness probe to use the same configuration mechanism. A new option,`RACECAR_LIVENESS_PROBE_SKIP_CONFIG_FILES` ensures this doesn't happen.

Avoid loading config files when executing the liveness probe check

---

lib/racecar/producer.rb
spec/producer_spec.rb

Globally configured partitioner is not being correctly passed on to the internal rdkafka producer in the new standalone Racecar producer. This patch fixes this issue
This config was added to racecar in https://github.com/zendesk/racecar/pull/306 but we missed to add it in the standalone producer

Ensure partitioner is correctly passed to internal producer

---

.github/workflows/ci.yml
README.md
docker-compose.yml

Docker Compose v2 uses `docker compose` command instead of `docker-compose`: https://docs.docker.com/compose/releases/migrate/

replace docker-compose with docker compose in tests

---

.rspec
spec/datadog_spec.rb

Enables random order in RSpec, fixes Datadog-related specs (we need to reset Datadog configuration before each of them).

run specs in random order

---

.github/workflows/ci.yml
CHANGELOG.md
Gemfile
Gemfile.lock
racecar.gemspec
spec/support/integration_helper.rb

Adds tests with Ruby 3.4. I’ve also updated the version of Active Support that we use in tests and added the same Ruby versions matrix for integration tests (they take only about a minute).

Add tests with Ruby 3.4

---

CHANGELOG.md
Gemfile.lock
lib/racecar/consumer.rb
racecar.gemspec
spec/integration/cooperative_sticky_assignment_spec.rb
spec/runner_spec.rb

This PR completes a housekeeping item:
* Allow rdkafka versions newer than 0.15.0

Allow rdkafka versions newer than 0.15.0

---

docker-compose.yml

5.5.1 is the version from the first commit for docker-compose.yml: https://github.com/zendesk/racecar/commit/d2b97e3e281a022751bda133f8eff7cc79c0bec5
This was five years ago, and we can use newer versions of these images. Unlike 5.5.1, these images are multi-arch, so you can now run `docker compose` on ARM processors.

update zookeeper and kafka images in docker compose

---

.github/workflows/ci.yml
.github/workflows/publish.yml
README.md
Rakefile

Switches to [a Trusted Publishing workflow](https://guides.rubygems.org/trusted-publishing/).
This workflow will run whenever `version.rb` is changed in the `main` branch.
Setting `ENV["gem_push"]` is also not necessary anymore.
This workflow relies on the main branch being named `main`. Please rename it (`main` is the standard name across Zendesk).
`bundler-cache` for `setup-ruby` is set to false to prevent [cache poisoning attacks](https://adnanthekhan.com/2024/05/06/the-monsters-in-your-build-cache-github-actions-cache-poisoning/).
Finally, we add a description of the new release process. Our README and CONTRIBUTING files don’t have a standard structure, so please check that we have updated a correct file and that the new section makes sense for this gem.

Switch to trusted publishing workflow and run it on version.rb changes
