README.md
lib/racecar/config.rb
lib/racecar/env_loader.rb
spec/config_spec.rb

Allows configuring most variables using the ENV.

Allow configuring most things by setting ENV variables

---

exe/racecarctl
lib/racecar/cli.rb
lib/racecar/config_loader.rb
lib/racecar/ctl.rb

* Allows producing messages to Kafka.
I would like to add the ability to reset consumer groups, pause/unpause partitions, etc.

Add racecarctl, a Racecar controller executable

---

README.md
lib/racecar/config.rb
lib/racecar/runner.rb
spec/config_spec.rb

Introspect the consumer on SIGUSR1

---

.gitignore
examples/batch_consumer.rb
lib/racecar/runner.rb
spec/runner_spec.rb

Batch processing

---

README.md
lib/racecar/config.rb

Pause for 10 seconds by default

---

lib/racecar/rails_config_file_loader.rb

I improved the rails app and config loading by doing this:
1. Don't swallow too many `LoadError`
2. Only load the configuration file if it is present.

Better rails loading

---

lib/racecar/runner.rb

Looks like the SASL options weren't passed in.

Pass in the SASL options

---

lib/racecar/config.rb
lib/racecar/runner.rb

Allow pausing partitions indefinitely

---

README.md
lib/racecar/config.rb
lib/racecar/runner.rb

Support configuring SASL SCRAM

---

racecar.gemspec

This version allows restricting the allowed values for a variable.

Bump dependency on KingKonf to v0.2.0

---

lib/racecar/config.rb

Otherwise the default will be "debug".

Set the log level to "info" by default

---

lib/racecar/runner.rb

This fixes #86 with the hack to create a thread and join it again that
was mentioned in this issue.

Fix graceful shutdown

---

racecar.gemspec

This PR allows installing the gem using latest bundler.

Allow using Bundler 2

---

lib/racecar/datadog.rb

Fixes instrumentation for producers.

Fix producer instrumentation subscription

---

lib/racecar/config.rb
lib/racecar/consumer_set.rb

Add `fetch.min.bytes` as a configuration.

Expose fetch.min.bytes

---

racecar.gemspec

Bump rdkafka to 0.8.0
https://github.com/appsignal/rdkafka-ruby/blob/main/CHANGELOG.md#080

Bump rdkafka to 0.8.0

---

.github/dependabot.yml

Adds dependabot for gem update

adds dependabot to project

---

README.md

- Add new section "Compression" to update the required library for Racecar v2
- Updated the "Handling Error Section" to link "Compression"

add error related to compression

---

lib/racecar/consumer_set.rb
spec/consumer_set_spec.rb

Fixes https://github.com/zendesk/racecar/issues/335

Fix pause and resume bug

---

lib/racecar/ctl.rb

Follow up from https://github.com/zendesk/racecar/pull/355#discussion_r1351667621

Avoid loading all of rails for liveness probe
